[theme]
primaryColor = "#FF0000"
backgroundColor = "#F0F2F6"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#262730"
font = "sans serif"

[client]
showErrorDetails = true

[logger]
level = "info"

[server]
port = 8501
headless = true
runOnSave = true
